/* eslint-disable prefer-const */
// eslint-disable-next-line prefer-const, import/no-mutable-exports
let arraySelect = [];
let arrayEmpresa = [];

const funcionDeAceptar = () => {
  const modal = document.getElementById('modalAlert');
  modal.style.display = 'none';
};

const funcionDeCancelar = () => {
  const modal = document.getElementById('modalAlert');
  modal.style.display = 'none';
};
const funcionDeOk = () => {
  const modal = document.getElementById('modalAlert');
  modal.style.display = 'none';
};
const funcionDeClose = () => {
  const modal = document.getElementById('modalAlert');
  modal.style.display = 'none';
};

const closeVentanaVerdeRoja = () => {
  const modal = document.getElementById('modalAlert');
  modal.style.display = 'none';
};

const arrayGlobal = {
  arraySelect,
  arrayEmpresa,
};

const objAlertaAceptarCancelar = {
  titulo: {
    text: 'Ejemplo de Alerta',
    fontSize: '20px',
    fontColor: '#212121',
    marginTop: '30px',
    display: 'block',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    alignSelf: 'center',
    className: 'titulo',
  },
  span: {
    text: 'Esta es una prueba para mensaje de alerta.',
    fontSize: '14px',
    fontColor: '#212121',
    marginTop: '0px',
    display: 'block',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    alignSelf: 'center',
    className: 'comentarios',
    fontWeight: 'bold',
    cursor: null,
    padding: null,
    position: null,
    top: null,
    right: null,
    left: null,
    hoverBackground: null,
    hoverColor: null,
    innerHTML: null,
  },
  btnaccept: {
    text: 'Aceptar',
    fontSize: '14px',
    fontColor: '#ffffff',
    backColor: '#212121',
    marginTop: '10px',
    display: 'block',
    fontWeight: 700,
    width: '100%',
    height: '40px',
    border: 'none',
    className: 'aceptar',
    cursor: 'pointer',
    borderRadius: '5px',
    hoverBackground: '#cecece',
    hoverColor: '#000000',
    onClick: funcionDeAceptar,
  },
  btncancel: {
    text: 'Cancelar',
    fontSize: '14px',
    fontColor: '#212121',
    backColor: '#ffffff',
    marginTop: '10px',
    display: 'block',
    fontWeight: 700,
    width: '100%',
    height: '40px',
    border: '3px solid #000000',
    className: 'cancelar',
    cursor: 'pointer',
    borderRadius: '5px',
    hoverBackground: '#cecece',
    hoverColor: '#000000',
    onClick: funcionDeCancelar,
  },
  btnok: {
    text: 'Ok',
    fontSize: '14px',
    fontColor: '#ffffff',
    backColor: '#212121',
    marginTop: '10px',
    display: 'none',
    fontWeight: 700,
    width: '100%',
    height: '40px',
    border: 'none',
    className: 'ok',
    cursor: 'pointer',
    borderRadius: '5px',
    hoverBackground: '#cecece',
    hoverColor: '#000000',
    onClick: funcionDeOk,
  },
  divContent: {
    position: 'relative',
    borderRadius: '10px',
    width: '300px',
    height: '200px',
    background: '#ffffff',
    border: '3px solid #000000',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.2)',
    margin: '20% auto',
    display: 'flex',
    flexDirection: 'column',
    padding: '10px',
    overflow: 'hidden',
    className: 'modal-content',
    textAlign: '',
    gap: '0px',
    top: null,
  },
  divButtons: {
    position: '',
    borderRadius: '5px',
    width: '300px',
    height: '200px',
    background: '#ffffff',
    border: 'none',
    boxShadow: '',
    margin: '0',
    display: 'block',
    flexDirection: '',
    padding: '2px 2px 2px 2px',
    overflow: 'hidden',
    className: 'div-button',
    textAlign: 'center',
    gap: '10px',
    top: null,
  },
  close: {
    text: 'x ',
    fontSize: '18px',
    fontColor: '#cecece',
    marginTop: '0px',
    display: 'block',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    alignSelf: 'center',
    className: 'modal-close',
    fontWeight: 'bold',
    cursor: 'pointer',
    padding: '10px 20px',
    position: 'absolute',
    top: '0',
    right: '0',
    left: null,
    hoverBackground: null,
    hoverColor: 'red',
    innerHTML: '&times',
    onClick: funcionDeClose,
  },
};

const avisoVerde = {
  close: {
    text: 'x ',
    fontSize: '18px',
    fontColor: '#ffffff',
    marginTop: '0px',
    display: 'block',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    alignSelf: 'center',
    className: 'verde-close',
    fontWeight: 'bold',
    cursor: 'pointer',
    padding: '10px 10px',
    position: 'absolute',
    top: '0',
    right: '0',
    left: null,
    hoverBackground: null,
    hoverColor: 'red',
    innerHTML: '&times',
    onClick: closeVentanaVerdeRoja,
  },
  div: {
    position: 'relative',
    borderRadius: '10px',
    width: '305px',
    height: '100px',
    background: '#21D849',
    border: 'none',
    boxShadow: 'none',
    margin: '20% auto',
    display: 'flex',
    flexDirection: 'column',
    padding: '10px',
    overflow: 'hidden',
    className: 'div-verde',
    textAlign: '',
    gap: '0px',
    top: '550px',
  },
  span: {
    text: '¡Proceso completado con éxito! Todos los pasos del procedimiento se han ejecutado correctamente.',
    fontSize: '12px',
    fontColor: '#ECECEC',
    marginTop: '0px',
    display: 'block',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    alignSelf: 'center',
    className: 'comentarios',
    fontWeight: '500',
    cursor: null,
    padding: '15px 15px 15px 15px',
    position: null,
    top: null,
    right: null,
    left: null,
    hoverBackground: null,
    hoverColor: null,
    innerHTML: null,
  },
};
const avisoAmarillo = {
  close: {
    text: 'x ',
    fontSize: '18px',
    fontColor: '#ffffff',
    marginTop: '0px',
    display: 'block',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    alignSelf: 'center',
    className: 'verde-close',
    fontWeight: 'bold',
    cursor: 'pointer',
    padding: '10px 10px',
    position: 'absolute',
    top: '0',
    right: '0',
    left: null,
    hoverBackground: null,
    hoverColor: 'red',
    innerHTML: '&times',
    onClick: closeVentanaVerdeRoja,
  },
  div: {
    position: 'relative',
    borderRadius: '10px',
    width: '305px',
    height: '100px',
    background: '#e5a110',
    border: 'none',
    boxShadow: 'none',
    margin: '20% auto',
    display: 'flex',
    flexDirection: 'column',
    padding: '10px',
    overflow: 'hidden',
    className: 'div-verde',
    textAlign: '',
    gap: '0px',
    top: '550px',
  },
  span: {
    text: 'El proceso puede demorar unos instantes hasta que se visualice la imágen en la celda correpondiente.',
    fontSize: '12px',
    fontColor: '#ffffff',
    marginTop: '0px',
    display: 'block',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    alignSelf: 'center',
    className: 'comentarios',
    fontWeight: '500',
    cursor: null,
    padding: '15px 15px 15px 15px',
    position: null,
    top: null,
    right: null,
    left: null,
    hoverBackground: null,
    hoverColor: null,
    innerHTML: null,
  },
};
const avisoRojo = {
  close: {
    text: 'x ',
    fontSize: '18px',
    fontColor: '#ffffff',
    marginTop: '0px',
    display: 'block',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    alignSelf: 'center',
    className: 'verde-close',
    fontWeight: 'bold',
    cursor: 'pointer',
    padding: '10px 10px',
    position: 'absolute',
    top: '0',
    right: '0',
    left: null,
    hoverBackground: null,
    hoverColor: 'red',
    innerHTML: '&times',
    onClick: closeVentanaVerdeRoja,
  },
  div: {
    position: 'relative',
    borderRadius: '10px',
    width: '305px',
    height: '100px',
    background: '#D82137',
    border: 'none',
    boxShadow: 'none',
    margin: '20% auto',
    display: 'flex',
    flexDirection: 'column',
    padding: '10px',
    overflow: 'hidden',
    className: 'div-verde',
    textAlign: '',
    gap: '0px',
    top: '550px',
  },
  span: {
    text: 'Hubo un error que no permite continuar con el proceso correcto.',
    fontSize: '12px',
    fontColor: '#ffffff',
    marginTop: '0px',
    display: 'block',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    alignSelf: 'center',
    className: 'comentarios',
    fontWeight: '500',
    cursor: null,
    padding: '15px 15px 15px 15px',
    position: null,
    top: null,
    right: null,
    left: null,
    hoverBackground: null,
    hoverColor: null,
    innerHTML: null,
  },
};

export default {
  arrayGlobal,
  objAlertaAceptarCancelar,
  avisoVerde,
  avisoAmarillo,
  avisoRojo,
};
